### ISSUE TITLE
Arduboy Community in read-only mode

### ISSUE THREAD

**Issue by SimonMerrett** [SimonMerrett/Arduboy2#1]
Wasn't sure how best to get in touch with @Pharap, @MLXXXp and see if you know what's going on.

**Comment by MLXXXp** [comment]
@SimonMerrett,
I don't know. Kevin B. must be doing something. I can't log in.

**Comment by SimonMerrett** [comment]
Well thanks for confirming it's not a local issue to me. Was like that last night for me too.

**Comment by MLXXXp** [comment]
> Was like that last night for me too.

Same here.

**Comment by Pharap** [comment]
I know for definite that Kevin must have accessed the server's database to do something specific because of a certain change that's fairly easy to spot with a moderator's account but probably less so for most standard users.
The site has to go into read-only mode to do that, and it most likely got left in read-only mode by accident.

Either way, it's back up and running now, so I guess that makes this a resolved issue?
